# =============================================================================
# Pat Fortress - Loki Configuration
# Comprehensive Log Aggregation and Storage
# =============================================================================

auth_enabled: false

# =============================================================================
# Server Configuration
# =============================================================================
server:
  http_listen_port: 3100
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  http_server_idle_timeout: 120s
  log_level: info
  log_format: json

# =============================================================================
# Ingester Configuration
# =============================================================================
ingester:
  lifecycler:
    address: 0.0.0.0
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0
  chunk_target_size: 1048576
  chunk_block_size: 262144
  chunk_encoding: gzip
  max_chunk_age: 10m
  
  # WAL Configuration for data durability
  wal:
    enabled: true
    dir: /loki/wal
    checkpoint_duration: 5m
    flush_on_shutdown: true

# =============================================================================
# Schema Configuration
# =============================================================================
schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: fortress_index_
        period: 24h

# =============================================================================
# Storage Configuration
# =============================================================================
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    shared_store: filesystem
    cache_ttl: 24h
    
  filesystem:
    directory: /loki/chunks

# =============================================================================
# Limits Configuration
# =============================================================================
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  max_label_name_length: 1024
  max_label_value_length: 4096
  max_label_names_per_series: 30
  max_line_size: 256kb
  max_entries_limit_per_query: 5000
  max_streams_per_user: 10000
  max_global_streams_per_user: 5000
  unordered_writes: true
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB
  max_chunks_per_query: 2000000
  max_query_length: 721h
  max_query_parallelism: 32
  cardinality_limit: 100000
  max_streams_matchers_per_query: 1000
  max_concurrent_tail_requests: 10
  retention_period: 744h  # 31 days

# =============================================================================
# Chunk Store Configuration  
# =============================================================================
chunk_store_config:
  max_look_back_period: 0s
  chunk_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_items: 1024
      ttl: 24h
  write_dedupe_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_items: 1024
      ttl: 10m

# =============================================================================
# Table Manager Configuration
# =============================================================================
table_manager:
  retention_deletes_enabled: true
  retention_period: 744h  # 31 days
  poll_interval: 2m
  creation_grace_period: 10m
  index_tables_provisioning:
    enable_ondemand_throughput_mode: false
    provisioned_write_throughput: 1
    provisioned_read_throughput: 1
    enable_inactive_throughput_on_demand_mode: false
    inactive_write_throughput: 1
    inactive_read_throughput: 1

# =============================================================================
# Query Range Configuration
# =============================================================================
query_range:
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_items: 1024
        ttl: 1h
  cache_results: true
  max_retries: 5
  split_queries_by_interval: 15m
  align_queries_with_step: true
  parallelise_shardable_queries: true

# =============================================================================
# Query Frontend Configuration
# =============================================================================
frontend:
  max_outstanding_per_tenant: 256
  compress_responses: true
  log_queries_longer_than: 10s

# =============================================================================
# Ruler Configuration (for alerting)
# =============================================================================
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true

# =============================================================================
# Distributor Configuration
# =============================================================================
distributor:
  ring:
    kvstore:
      store: inmemory

# =============================================================================
# Compactor Configuration
# =============================================================================
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# =============================================================================
# Analytics Configuration
# =============================================================================
analytics:
  reporting_enabled: false

# =============================================================================
# Common Configuration
# =============================================================================
common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

# =============================================================================
# Runtime Configuration
# =============================================================================
runtime_config:
  file: /loki/runtime.yaml