# =============================================================================
# Pat Fortress - Jaeger Configuration
# Comprehensive Distributed Tracing Configuration
# =============================================================================

# =============================================================================
# Collector Configuration
# =============================================================================
collector:
  # Port configuration
  grpc-port: 14250
  http-port: 14268
  
  # Queue configuration
  queue:
    size: 2000
    num-workers: 50
  
  # Zipkin compatibility
  zipkin:
    host-port: ":9411"
    
  # Log level
  log-level: info
  
  # Health check configuration
  admin:
    http:
      host-port: ":14269"

# =============================================================================
# Agent Configuration  
# =============================================================================
agent:
  # Processor configuration
  processor:
    jaeger-compact:
      workers: 10
      server-host-port: ":6831"
      server-max-packet-size: 65000
      server-queue-size: 1000
      
    jaeger-binary:
      workers: 10
      server-host-port: ":6832"
      server-max-packet-size: 65000
      server-queue-size: 1000
      
    zipkin-compact:
      workers: 10
      server-host-port: ":5775"
      
  # Reporter configuration
  reporter:
    grpc:
      host-port: "jaeger-collector:14250"
      retry:
        max: 3
      connection-timeout: 1s
    
    # Log spans to stdout for debugging
    log-spans: false

# =============================================================================
# Query Configuration
# =============================================================================
query:
  # Port configuration
  port: 16686
  
  # Base path for UI
  base-path: /jaeger
  
  # Static files path
  static-files: /go/jaeger-ui/
  
  # UI configuration
  ui-config: |
    {
      "archiveEnabled": true,
      "dependencies": {
        "menuEnabled": true
      },
      "menu": [
        {
          "label": "Fortress Documentation",
          "url": "https://fortress.pat.local/docs"
        },
        {
          "label": "Grafana Dashboards", 
          "url": "https://fortress.pat.local/grafana"
        }
      ]
    }
    
  # Search configuration  
  max-traces: 20000
  default-search-limit: 20
  
  # Health check
  admin:
    http:
      host-port: ":16687"

# =============================================================================
# Storage Configuration
# =============================================================================
storage:
  type: badger
  
  # Badger configuration (for single-node deployments)
  badger:
    ephemeral: false
    directory-key: /badger/key
    directory-value: /badger/data
    consistency: false
    maintenance-interval: 5m
    metrics-update-interval: 10s
    
    # TTL configuration
    span-store-ttl: 168h  # 7 days
    read-only: false

# Alternative Elasticsearch configuration (for production)
# storage:
#   type: elasticsearch
#   elasticsearch:
#     server-urls: http://elasticsearch:9200
#     index-prefix: fortress-jaeger
#     username: elastic
#     password: changeme
#     sniffer: false
#     max-span-age: 168h  # 7 days
#     num-shards: 5
#     num-replicas: 1
#     bulk:
#       size: 5000000  # 5MB
#       workers: 1
#       actions: 1000
#       flush-interval: 200ms

# =============================================================================
# Sampling Configuration
# =============================================================================
sampling:
  # Default sampling strategy
  default_strategy:
    type: adaptive
    max_traces_per_second: 100
    
  # Per-service sampling strategies
  per_service_strategies:
    - service: "fortress-core"
      type: probabilistic
      param: 0.5  # 50% sampling
      
    - service: "fortress-smtp"  
      type: probabilistic
      param: 0.3  # 30% sampling
      
    - service: "fortress-api"
      type: probabilistic  
      param: 0.8  # 80% sampling
      
    - service: "fortress-plugins"
      type: probabilistic
      param: 0.1  # 10% sampling (high volume)
      
    - service: "fortress-workflows"
      type: probabilistic
      param: 1.0  # 100% sampling (critical)
      
    - service: "fortress-frontend"
      type: probabilistic
      param: 0.2  # 20% sampling
      
  # Operation-specific strategies
  per_operation_strategies:
    - service: "fortress-api"
      operation: "GraphQL:IntrospectionQuery"
      type: probabilistic
      param: 0.01  # 1% sampling for introspection
      
    - service: "fortress-core"
      operation: "health_check"  
      type: probabilistic
      param: 0.01  # 1% sampling for health checks

# =============================================================================
# Processing Configuration
# =============================================================================
processor:
  # Batch processing configuration
  batch:
    timeout: 1s
    send_batch_size: 8192
    send_batch_max_size: 8192
    
  # Memory limiter
  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128
    check_interval: 5s

# =============================================================================
# Ingester Configuration (for Jaeger v2)
# =============================================================================
ingester:
  # Trace processing
  max_trace_lookback: 72h
  
  # Ring configuration  
  ring:
    heartbeat_timeout: 1m
    tokens_file_path: /jaeger/tokens
    
  # Trace batching
  trace_batch_size: 50
  
  # Lifecycler
  lifecycler:
    heartbeat_period: 15s
    join_after: 30s
    observe_period: 30s
    num_tokens: 128

# =============================================================================
# GRPC Configuration
# =============================================================================
grpc:
  server:
    max_connection_idle: 30s
    max_connection_age: 30s
    max_connection_age_grace: 5s
    time: 5s
    timeout: 1s
    
  client:
    timeout: 1s
    
# =============================================================================
# Metrics Configuration
# =============================================================================
metrics:
  # Prometheus metrics
  prometheus:
    namespace: jaeger
    
  # HTTP metrics server
  http:
    host-port: ":8888"

# =============================================================================
# Health Check Configuration
# =============================================================================
health_check:
  http:
    host-port: ":8080"

# =============================================================================
# Multi-tenancy Configuration
# =============================================================================
multi_tenancy:
  enabled: true
  tenant_header: "X-Tenant-ID"
  tenant_label: "tenant_id"
  
  # Default tenant for requests without header
  default_tenant_id: "fortress"

# =============================================================================
# Archive Configuration
# =============================================================================
archive:
  # Enable trace archiving to long-term storage
  enabled: true
  
  # Archive after this duration
  max_age: 168h  # 7 days
  
  # Batch size for archiving
  batch_size: 1000

# =============================================================================
# Adaptive Sampling Configuration
# =============================================================================
adaptive_sampling:
  # Enable adaptive sampling
  enabled: true
  
  # Sampling server configuration
  sampling_server_url: http://jaeger-collector:14268
  
  # Max traces per second per service
  max_traces_per_second: 500
  
  # Aggregation buckets
  aggregation_buckets: 10
  
  # How often to calculate new sampling rates
  calculation_interval: 1m
  
  # How often to poll for sampling strategies
  aggregation_interval: 10s

# =============================================================================
# Dependencies Configuration
# =============================================================================
dependencies:
  # Enable dependency calculation
  enabled: true
  
  # How often to calculate dependencies
  interval: 1m
  
  # Lookback period for dependency calculation  
  lookback: 24h