# =============================================================================
# Pat Fortress - Kubernetes ConfigMaps
# =============================================================================

---
# Fortress Core Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: fortress-core-config
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: pat-fortress
data:
  fortress.yaml: |
    server:
      port: 8025
      host: "0.0.0.0"
      timeout: 30s
      read_timeout: 10s
      write_timeout: 10s
      graceful_shutdown: 30s
    
    database:
      max_connections: 100
      max_idle_connections: 10
      connection_max_lifetime: 3600s
      ssl_mode: require
      migration_timeout: 300s
    
    redis:
      pool_size: 100
      max_retries: 3
      retry_delay: 100ms
      dial_timeout: 5s
      read_timeout: 3s
      write_timeout: 3s
    
    kafka:
      consumer_group: fortress-core
      session_timeout: 30s
      heartbeat_interval: 3s
      max_processing_time: 300s
    
    security:
      jwt_expiry: 24h
      refresh_token_expiry: 168h
      password_min_length: 12
      max_login_attempts: 5
      lockout_duration: 300s
    
    features:
      rate_limiting: true
      metrics: true
      tracing: true
      health_checks: true

---
# SMTP Server Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: fortress-smtp-config
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress
    app.kubernetes.io/component: smtp
    app.kubernetes.io/part-of: pat-fortress
data:
  smtp.yaml: |
    smtp:
      port: 1025
      host: "0.0.0.0"
      max_connections: 1000
      max_message_size: 52428800  # 50MB
      timeout: 300s
      auth_enabled: false
      tls_enabled: false
      max_recipients: 100
      max_hop_count: 25
    
    processing:
      async_processing: true
      worker_pool_size: 50
      queue_buffer_size: 1000
      batch_size: 100
      batch_timeout: 5s
    
    validation:
      domain_validation: true
      spf_check: false
      dkim_verification: false
      spam_filtering: false
    
    storage:
      retention_days: 30
      cleanup_interval: 3600s
      compression: true

---
# GraphQL API Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: fortress-api-config
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: pat-fortress
data:
  api.yaml: |
    server:
      port: 8025
      cors:
        enabled: true
        origins: ["https://fortress.pat.local", "https://*.pat.local"]
        methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
        headers: ["Authorization", "Content-Type", "X-Requested-With"]
        credentials: true
    
    graphql:
      playground: false
      introspection: false
      max_query_complexity: 1000
      max_query_depth: 10
      timeout: 30s
    
    rate_limiting:
      enabled: true
      requests_per_minute: 1000
      burst: 100
      key_generator: "ip_and_user"
    
    subscriptions:
      enabled: true
      max_connections: 10000
      connection_timeout: 60s
      keep_alive_interval: 30s
    
    file_upload:
      max_file_size: 10485760  # 10MB
      allowed_types: ["image/png", "image/jpeg", "text/plain", "application/json"]
      upload_path: "/app/uploads"

---
# Plugin Runtime Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: fortress-plugins-config
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress
    app.kubernetes.io/component: plugins
    app.kubernetes.io/part-of: pat-fortress
data:
  plugins.yaml: |
    runtime:
      port: 8026
      max_concurrent_plugins: 50
      plugin_timeout: 30s
      isolation_enabled: true
      network_access: "restricted"
      filesystem_access: "sandbox"
    
    resources:
      max_memory: 128Mi
      max_cpu: 0.5
      max_disk: 100Mi
      max_execution_time: 30s
    
    security:
      sandboxing: true
      capability_filtering: true
      syscall_filtering: true
      network_policies: true
    
    languages:
      javascript:
        enabled: true
        runtime: "node18"
        timeout: 30s
      python:
        enabled: true
        runtime: "python311"
        timeout: 30s
      go:
        enabled: true
        timeout: 30s

---
# Workflow Engine Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: fortress-workflows-config
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress
    app.kubernetes.io/component: workflows
    app.kubernetes.io/part-of: pat-fortress
data:
  workflows.yaml: |
    engine:
      port: 8027
      max_concurrent_workflows: 200
      workflow_timeout: 300s
      retry_attempts: 3
      retry_delay: 5s
      state_persistence: true
      event_sourcing: true
    
    scheduler:
      poll_interval: 1s
      batch_size: 50
      worker_pool_size: 20
    
    state_management:
      checkpoint_interval: 60s
      snapshot_threshold: 1000
      cleanup_interval: 3600s
      retention_days: 30
    
    notifications:
      webhook_timeout: 10s
      email_timeout: 30s
      retry_attempts: 3

---
# Nginx Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: fortress-nginx-config
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: pat-fortress
data:
  nginx.conf: |
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;
    
    events {
        worker_connections 4096;
        use epoll;
        multi_accept on;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        # Security headers
        add_header X-Frame-Options DENY always;
        add_header X-Content-Type-Options nosniff always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self' wss:;" always;
        
        # Performance
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        client_max_body_size 50M;
        
        # Gzip compression
        gzip on;
        gzip_vary on;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml text/javascript application/javascript application/xml+rss application/json;
        
        # Rate limiting
        limit_req_zone $binary_remote_addr zone=api:10m rate=100r/m;
        limit_req_zone $binary_remote_addr zone=smtp:10m rate=1000r/m;
        
        # Upstream definitions
        upstream fortress-frontend {
            server fortress-frontend-service:3000 max_fails=3 fail_timeout=30s;
        }
        
        upstream fortress-api {
            server fortress-api-service:8025 max_fails=3 fail_timeout=30s;
        }
        
        upstream fortress-smtp {
            server fortress-smtp-service:1025 max_fails=3 fail_timeout=30s;
        }
        
        # HTTP to HTTPS redirect
        server {
            listen 80;
            server_name fortress.pat.local *.pat.local;
            return 301 https://$server_name$request_uri;
        }
        
        # Main HTTPS server
        server {
            listen 443 ssl http2;
            server_name fortress.pat.local;
            
            ssl_certificate /etc/nginx/ssl/fortress.crt;
            ssl_certificate_key /etc/nginx/ssl/fortress.key;
            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384;
            ssl_prefer_server_ciphers on;
            ssl_session_cache shared:SSL:10m;
            ssl_session_timeout 10m;
            
            # Frontend
            location / {
                proxy_pass http://fortress-frontend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            # API
            location /api/ {
                limit_req zone=api burst=200 nodelay;
                proxy_pass http://fortress-api;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 300s;
                proxy_send_timeout 300s;
            }
            
            # WebSocket for GraphQL subscriptions
            location /ws/ {
                proxy_pass http://fortress-api;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 3600s;
                proxy_send_timeout 3600s;
            }
        }
        
        # SMTP Proxy (TCP)
        stream {
            upstream fortress-smtp-stream {
                server fortress-smtp-service:1025 max_fails=3 fail_timeout=30s;
            }
            
            server {
                listen 1025;
                proxy_pass fortress-smtp-stream;
                proxy_timeout 300s;
                proxy_connect_timeout 5s;
            }
        }
    }