# =============================================================================
# Pat Fortress - Kubernetes Persistent Volumes & Claims
# =============================================================================

---
# PostgreSQL Primary PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortress-postgres-primary-pvc
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: pat-fortress
    app.kubernetes.io/instance: primary
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fortress-ssd-storage
  volumeMode: Filesystem

---
# PostgreSQL Replica PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortress-postgres-replica-pvc
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: pat-fortress
    app.kubernetes.io/instance: replica
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fortress-ssd-storage
  volumeMode: Filesystem

---
# Redis Master PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortress-redis-master-pvc
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress-redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: pat-fortress
    app.kubernetes.io/instance: master
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: fortress-ssd-storage
  volumeMode: Filesystem

---
# Kafka PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortress-kafka-pvc
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress-kafka
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: pat-fortress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fortress-ssd-storage
  volumeMode: Filesystem

---
# Fortress Storage PVC (shared across core services)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortress-storage-pvc
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: pat-fortress
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: fortress-nfs-storage
  volumeMode: Filesystem

---
# Email Storage PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortress-email-storage-pvc
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress-smtp
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: pat-fortress
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: fortress-nfs-storage
  volumeMode: Filesystem

---
# API Uploads PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortress-api-uploads-pvc
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress-api
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: pat-fortress
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: fortress-nfs-storage
  volumeMode: Filesystem

---
# Plugin Storage PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortress-plugin-storage-pvc
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress-plugins
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: pat-fortress
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: fortress-nfs-storage
  volumeMode: Filesystem

---
# Workflow Storage PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortress-workflow-storage-pvc
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress-workflows
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: pat-fortress
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: fortress-nfs-storage
  volumeMode: Filesystem

---
# Monitoring Storage PVC (Prometheus)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortress-prometheus-pvc
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress-prometheus
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: pat-fortress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fortress-ssd-storage
  volumeMode: Filesystem

---
# Grafana Storage PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortress-grafana-pvc
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress-grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: pat-fortress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fortress-ssd-storage
  volumeMode: Filesystem

---
# Loki Storage PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fortress-loki-pvc
  namespace: fortress
  labels:
    app.kubernetes.io/name: fortress-loki
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: pat-fortress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: fortress-ssd-storage
  volumeMode: Filesystem

---
# Storage Classes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fortress-ssd-storage
  labels:
    app.kubernetes.io/part-of: pat-fortress
provisioner: kubernetes.io/aws-ebs  # Change based on cloud provider
parameters:
  type: gp3
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fortress-nfs-storage
  labels:
    app.kubernetes.io/part-of: pat-fortress
provisioner: nfs.csi.k8s.io  # Or use your NFS CSI driver
parameters:
  server: fortress-nfs-server.fortress.svc.cluster.local
  share: /fortress/shared
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate