version: '3.8'

services:
  pat:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: pat-server
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # HTTP/API
    environment:
      - PAT_SMTP_BIND_ADDR=0.0.0.0:1025
      - PAT_HTTP_BIND_ADDR=0.0.0.0:8025
      - PAT_LOG_LEVEL=debug
      - PAT_UI_WEB_PATH=/app/web
    volumes:
      - pat-data:/app/data
    restart: unless-stopped

volumes:
  pat-data:
